((nil . ((compilation-read-command . nil)
         (projectile-run-use-comint-mode . t)
         (projectile-project-compilation-dir . "extra/gd32usb-test")
         (projectile-project-compilation-cmd . "make")
         (projectile-project-run-cmd . "make gdb")))
 (c-mode . ((indent-tabs-mode . nil)
            (c-basic-offset . 4)
            (c-file-style . "linux")))
 (c++-mode . ((indent-tabs-mode . nil)
              (c-basic-offset . 4)
              (c-file-style . "linux"))))
